### ISSUE TITLE
UnsupportedPlatformException message can use an improvement

### ISSUE THREAD

**Issue by nanaya** [flavorjones/tailwindcss-ruby#20]
The message says to [install the cli version manually](https://github.com/flavorjones/tailwindcss-ruby/blob/c4a21ef6ce9bd0b2b58d74540eea914de99e90bd/lib/tailwindcss/ruby.rb#L42-L45) but I think it should also say to set `TAILWINDCSS_INSTALL_DIR` env after installation. Otherwise just installing it won't make the message go away.

Or maybe just link to [the relevant section in the readme file](https://github.com/flavorjones/tailwindcss-ruby#using-a-local-installation-of-tailwindcss) instead...

**Comment by flavorjones** [comment]
@nanaya Thanks for letting me know what you think. Are you up for creating a pull request to clarify this?
