### ISSUE TITLE
illegal hardware instruction on x86_64

### ISSUE THREAD

**Issue by bogdan** [flavorjones/tailwindcss-ruby#4]
I am getting the following error when trying `4.0.0.alpha.26` version:

```
$  /Users/bogdan/.rvm/gems/ruby-3.2.2/gems/tailwindcss-ruby-4.0.0.alpha.26-x86_64-darwin/exe/x86_64-darwin/tailwindcss
zsh: illegal hardware instruction
$ arch -x86_64 /Users/bogdan/.rvm/gems/ruby-3.2.2/gems/tailwindcss-ruby-4.0.0.alpha.26-x86_64-darwin/exe/x86_64-darwin/tailwindcss
zsh: illegal hardware instruction  arch -x86_64
```

System info:

```
 $ uname -a
Darwin prakriti.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 x86_64
```

Please advice how to debug or gather more information.

**Comment by flavorjones** [comment]
Hi, these executables are simply downloaded from https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.26 and repackaged.

Can you please confirm that the executable from that release has this problem? If so, then we can report it upstream.

**Comment by bogdan** [comment]
The exe downloaded from there is just fine:

```
$ ~/Downloads/tailwindcss-macos-arm64
≈ tailwindcss v4.0.0-alpha.26

Usage:
  tailwindcss [--input input.css] [--output output.css] [--watch] [options…]

Options:
  -i, --input ··········· Input file
  -o, --output ·········· Output file
  -w, --watch ··········· Watch for changes and rebuild as needed
  -m, --minify ·········· Optimize and minify the output
      --cwd ············· The current working directory [default: `.`]
```

**Comment by flavorjones** [comment]
@bogdan What kind of a machine are you on? Your uname reports both arm64 and x86_64 which is strange. You've downloaded the x86_64 flavor of the gem, but downloaded the arm64 version of the executable from the upstream releases.

Can you reply with the output from `gem env` and `ruby -v`?

**Comment by bogdan** [comment]
I am not sure why RVM installed ruby with arch x86_64 but not arm64.
I am not sure how ruby x86_64 binary is able to run while tailwind x86_64 binary is not.
Maybe the problem is that tailwindcss x64 binary can not run in simulated environments:

```
 $ arch -x86_64 ~/Downloads/tailwindcss-macos-x64
zsh: illegal hardware instruction  arch -x86_64 ~/Downloads/tailwindcss-macos-x64 
```

Maybe we need to report that.


Here is my setup:



```
$ uname -a
Darwin prakriti.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 x86_64
$ rvm list
 * ext-ruby-3.3.4-rbe1089c8ec [ x86_64 ]
   ruby-2.6.3 [ missing bin/ruby ]
   ruby-3.0.0 [ x86_64 ]
   ruby-3.0.2 [ x86_64 ]
   ruby-3.1.2 [ x86_64 ]
   ruby-3.2.2 [ x86_64 ]
=> ruby-3.3.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

```
$ type ruby
ruby is /Users/bogdan/.rvm/rubies/ruby-3.3.5/bin/ruby
$ type gem
gem is a shell function from /Users/bogdan/.rvm/scripts/override_gem
$ ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-darwin23]
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.16
  - RUBY VERSION: 3.3.5 (2024-09-03 patchlevel 100) [x86_64-darwin23]
  - INSTALLATION DIRECTORY: /Users/bogdan/.rvm/gems/ruby-3.3.5
  - USER INSTALLATION DIRECTORY: /Users/bogdan/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /Users/bogdan/.rvm/rubies/ruby-3.3.5/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/bogdan/.rvm/gems/ruby-3.3.5/bin
  - SPEC CACHE DIRECTORY: /Users/bogdan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/bogdan/.rvm/rubies/ruby-3.3.5/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-23
  - GEM PATHS:
     - /Users/bogdan/.rvm/gems/ruby-3.3.5
     - /Users/bogdan/.rvm/rubies/ruby-3.3.5/lib/ruby/gems/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/bogdan/.rvm/gems/ruby-3.3.5/bin
     - /Users/bogdan/.rvm/gems/ruby-3.3.5@global/bin
     - /Users/bogdan/.rvm/rubies/ruby-3.3.5/bin
     - /Users/bogdan/.rvm/bin
     - /Users/bogdan/Downloads/google-cloud-sdk/bin
     - /Users/bogdan/.nvm/versions/node/v20.11.1/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /Library/Apple/usr/bin
     - /Applications/VMware Fusion Tech Preview.app/Contents/Public
     - /usr/local/munki
     - /Users/bogdan/bin
     - /usr/local/Cellar/git/2.30.1/libexec/git-core
     - /Users/bogdan/bin
     - /Users/bogdan/.rvm/bin
     - /usr/local/Cellar/git/2.30.1/libexec/git-core
```

![image](https://github.com/user-attachments/assets/564a805f-85cf-4de5-bb12-c76d42efeb10)

**Comment by flavorjones** [comment]
OK, because your Ruby is an x86_64 binary, it's going to download the same architecture when it fetches native gems.

I have to ask why you're running that binary when your native architecture is arm64. Aren't you taking a huge performance penalty by doing that?

If you install an arm64 Ruby then everything will work correctly for you.

If you wish to report something upstream, please be prepared for the response to be, "use the arm64 executable".

**Comment by bogdan** [comment]
> I have to ask why you're running that binary when your native architecture is arm64. Aren't you taking a huge performance penalty by doing that?

After investigation I guess it was because RVM installed x86_64 as a default because homebrew was using x86_64 which itself used it because it was installed at the moment when homebrew didn't support arm64 yet.
I had to reinstall homebrew and all dependencies to make it work which quite take a while, but now it works fine.

Anyone if someone would need an instant solution to this problem, one may use the following:

``` sh
# Update version
curl -L -o bin/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v4.0.0-alpha.26/tailwindcss-macos-arm64
chmod a+x ./bin/tailwindcss
./bin/tailwindcss --help
TAILWINDCSS_INSTALL_DIR=bin rails tailwindcss:build
```

> If you wish to report something upstream, please be prepared for the response to be, "use the arm64 executable".

JS community is not very empathic 😢 .

**Comment by bogdan** [comment]
By the way, the error message could be better (especially for `watch`) when the wrong binary was used:

```
$ TAILWINDCSS_INSTALL_DIR=bin rails tailwindcss:build
NOTE: using TAILWINDCSS_INSTALL_DIR to find tailwindcss executable: bin
bin/rails aborted!
Command failed with SIGILL (signal 4): /Users/bogdan/makabu/brad/seven-figures/bin/tailwindcss

Tasks: TOP => tailwindcss:build
(See full trace by running task with --trace)
$
```

Watch literally doesn't output anything:

```
$ TAILWINDCSS_INSTALL_DIR=bin rails tailwindcss:watch
NOTE: using TAILWINDCSS_INSTALL_DIR to find tailwindcss executable: bin
$
```

**Comment by albertsgrc** [comment]
I'm getting the same exception when building a x86 docker image from an ARM laptop:

`docker buildx build --platform linux/amd64 ...`

Later on, during the build:

```
 > [build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
1.558 bin/rails aborted!
1.576 Command failed with SIGILL (signal 4): /usr/local/bundle/ruby/3.4.0/gems/tailwindcss-ruby-4.0.3-x86_64-linux-gnu/exe/x86_64-linux-gnu/tailwindcss
```

**Comment by kittrCZ** [comment]
> > I have to ask why you're running that binary when your native architecture is arm64. Aren't you taking a huge performance penalty by doing that?
> 
> After investigation I guess it was because RVM installed x86_64 as a default because homebrew was using x86_64 which itself used it because it was installed at the moment when homebrew didn't support arm64 yet. I had to reinstall homebrew and all dependencies to make it work which quite take a while, but now it works fine.
> 
> If someone would need an instant solution to this problem, one may use the following:
> 
> # Update version
> curl -L -o bin/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v4.0.0-alpha.26/tailwindcss-macos-arm64
> chmod a+x ./bin/tailwindcss
> ./bin/tailwindcss --help
> TAILWINDCSS_INSTALL_DIR=bin rails tailwindcss:build
> > If you wish to report something upstream, please be prepared for the response to be, "use the arm64 executable".
> 
> JS community is not very empathic 😢 .
> 
> Thanks for your help!

What a joke.

**Comment by GoudekettingRM** [comment]
@bogdan Thanks for your fix. I was breaking my brain as to why it wasn't working 😅
